spring:
  application:
    name: podsofkon
  servlet:
    multipart:
      max-request-size: 256MB
      max-file-size: 256MB
  datasource:
    url: "jdbc:oracle:thin:@gd740878851_tp?TNS_ADMIN=/podsofkon/creds"
    username: asdf
    password: asdf
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select 1 from dual
      connection-pool-name: cserverConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  templates:
    path: mail-templates

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks,loggers,mappings,prometheus"

server:
  tomcat:
    connection-upload-timeout: 600000
    connection-timeout: 600000
    max-swallow-size: 256MB
    max-http-form-post-size: 256MB

logging:
  level:
    oracle:
      spring:
        service: DEBUG

org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

openai:
  key: asdf